"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "../components/header";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "NEWZEENS",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <head>
        <title>NEWZEENS</title>
        <link rel="icon" href="static/public/favicon.ico" sizes="any" />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
      </head>

      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
